resource_registry:
    OS::TripleO::ComputeOvsDpdk::Net::SoftwareConfig: /home/stack/single-nic/computeovsdpdk.yaml
    OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/single-nic/controller.yaml

parameter_defaults:
    ControlPlaneDefaultRoute: 192.168.24.1
    ControlPlaneSubnetCidr: '24'
    DnsServers:
    - 192.168.24.1
    EC2MetadataIp: 192.168.24.1
    ExternalAllocationPools:
    -   end: 172.18.5.150
        start: 172.18.5.50
    ExternalInterfaceDefaultRoute: 172.18.5.1
    ExternalNetCidr: 172.18.5.0/24
    ExternalNetworkVlanID: 300
    InternalApiAllocationPools:
    -   end: 172.18.1.149
        start: 172.18.1.10
    InternalApiNetCidr: 172.18.1.0/24
    InternalApiNetworkVlanID: 301
    NeutronEnableDVR: 'false'
    NeutronNetworkType: geneve
    NeutronTunnelTypes: geneve
    StorageAllocationPools:
    -   end: 172.18.3.149
        start: 172.18.3.10
    StorageMgmtAllocationPools:
    -   end: 172.18.4.149
        start: 172.18.4.10
    StorageMgmtNetCidr: 172.18.4.0/24
    StorageMgmtNetworkVlanID: 303
    StorageNetCidr: 172.18.3.0/24
    StorageNetworkVlanID: 302
    TenantAllocationPools:
    -   end: 172.18.2.150
        start: 172.18.2.10
    TenantNetCidr: 172.18.2.0/24
    TenantNetworkVlanID: 304

    ComputeOvsDpdkParameters:
        KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=32 intel_iommu=on iommu=pt isolcpus=1-15,33-47,17-31,49-63"
        TunedProfileName: "cpu-partitioning"
        IsolCpusList: "1-15,33-47,17-31,49-63"
        OvsDpdkSocketMemory: "1024,1024"
        OvsDpdkMemoryChannels: "4"
        NovaReservedHostMemory: 2048
        OvsPmdCoreList: "1,2,3,33,34,35,17,49"
        OvsDpdkCoreList: "0,32,16,48"
        NovaComputeCpuDedicatedSet: ['4-15','36-47','18-31','50-63']
        NovaComputeCpuSharedSet: ['0','32','16','48']

    OvercloudControllerFlavor: "controller"
    OvercloudComputeOvsDpdkFlavor: "computeovsdpdk"

    ControllerCount: 1
    ComputeOvsDpdkCount: 1

    NeutronExternalNetworkBridge: "''"
    # The OVS logical->physical bridge mappings to use.
    NeutronBridgeMappings: 'dpdk0:br-link0,dpdk1:br-link1,access:br-access'
    NeutronNetworkVLANRanges: 'dpdk0:100:500,dpdk1:100:500,access:100:500'
    NeutronFlatNetworks: '*'



