resource_registry:
    OS::TripleO::ComputeOvsDpdk::Net::SoftwareConfig: /home/stack/single-nic/computeovsdpdk.yaml
    OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/single-nic/controller.yaml

parameter_defaults:
    ControlPlaneDefaultRoute: 192.168.16.1
    ControlPlaneSubnetCidr: '24'
    DnsServers:
    - 192.168.16.1
    EC2MetadataIp: 192.168.16.1
    ExternalAllocationPools:
    -   end: 172.18.5.150
        start: 172.18.5.50
    ExternalInterfaceDefaultRoute: 172.18.5.1
    ExternalNetCidr: 172.18.5.0/24
    ExternalNetworkVlanID: 300
    InternalApiAllocationPools:
    -   end: 172.18.1.149
        start: 172.18.1.10
    InternalApiNetCidr: 172.18.1.0/24
    InternalApiNetworkVlanID: 301
    NeutronNetworkType: vxlan
    NeutronTunnelTypes: vxlan
    StorageAllocationPools:
    -   end: 172.18.3.149
        start: 172.18.3.10
    StorageMgmtAllocationPools:
    -   end: 172.18.4.149
        start: 172.18.4.10
    StorageMgmtNetCidr: 172.18.4.0/24
    StorageMgmtNetworkVlanID: 303
    StorageNetCidr: 172.18.3.0/24
    StorageNetworkVlanID: 302
    TenantAllocationPools:
    -   end: 172.18.2.150
        start: 172.18.2.10
    TenantNetCidr: 172.18.2.0/24
    TenantNetworkVlanID: 304

    ComputeOvsDpdkParameters:
        KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=32 intel_iommu=on iommu=pt isolcpus=2,4,6,8,10,14,16,18,20,22,3,5,7,9,11,15,17,19,21,23"
        TunedProfileName: "cpu-partitioning"
        IsolCpusList: "2,4,6,8,10,14,16,18,20,22,3,5,7,9,11,15,17,19,21,23"
        OvsDpdkSocketMemory: "1024,1024"
        OvsDpdkMemoryChannels: "4"
        NovaReservedHostMemory: 2048
        OvsPmdCoreList: "2,14,3,15"
        OvsDpdkCoreList: "0,12,1,13"
        NovaVcpuPinSet: [4,6,8,10,16,18,20,22,5,7,9,11,17,19,21,23]

    NovaSchedulerDefaultFilters:
        - "RetryFilter"
        - "AvailabilityZoneFilter"
        - "RamFilter"
        - "ComputeFilter"
        - "ComputeCapabilitiesFilter"
        - "ImagePropertiesFilter"
        - "ServerGroupAntiAffinityFilter"
        - "ServerGroupAffinityFilter"
        - "PciPassthroughFilter"
        - "NUMATopologyFilter"
        - "AggregateInstanceExtraSpecsFilter"

    OvercloudControllerFlavor: "controller"
    OvercloudComputeOvsDpdkFlavor: "computeovsdpdk"

    ControllerCount: 1
    ComputeOvsDpdkCount: 1

    NeutronExternalNetworkBridge: "''"
    NeutronTunnelTypes: 'vxlan'
    NeutronNetworkType: 'vlan'
    # The OVS logical->physical bridge mappings to use.
    NeutronBridgeMappings: 'dpdk0:br-link0,dpdk1:br-link1,access:br-access'
    NeutronNetworkVLANRanges: 'dpdk0:100:500,dpdk1:100:500,access:100:500'
    NeutronFlatNetworks: '*'

