parameter_defaults:
    ControlPlaneDefaultRoute: 192.168.24.1
    ControlPlaneSubnetCidr: '24'
    DnsServers:
    - 192.168.24.1
    EC2MetadataIp: 192.168.24.1
    ExternalAllocationPools:
    -   end: 172.17.5.150
        start: 172.17.5.50
    ExternalInterfaceDefaultRoute: 172.17.5.1
    ExternalNetCidr: 172.17.5.0/24
    ExternalNetworkVlanID: 300
    InternalApiAllocationPools:
    -   end: 172.17.1.149
        start: 172.17.1.10
    InternalApiNetCidr: 172.17.1.0/24
    InternalApiNetworkVlanID: 301
    NeutronEnableDVR: 'false'
    NeutronNetworkType: vxlan
    NeutronTunnelTypes: vxlan
    StorageAllocationPools:
    -   end: 172.17.3.149
        start: 172.17.3.10
    StorageMgmtAllocationPools:
    -   end: 172.17.4.149
        start: 172.17.4.10
    StorageMgmtNetCidr: 172.17.4.0/24
    StorageMgmtNetworkVlanID: 303
    StorageNetCidr: 172.17.3.0/24
    StorageNetworkVlanID: 302
    TenantAllocationPools:
    -   end: 172.17.2.150
        start: 172.17.2.10
    TenantNetCidr: 172.17.2.0/24
    TenantNetworkVlanID: 304

    NumDpdkInterfaceRxQueues: 2
    ComputeOvsDpdkParameters:
        KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=128 intel_iommu=on iommu=pt isolcpus=1-15,33-47,17-31,49-63"
        TunedProfileName: "cpu-partitioning"
        IsolCpusList: "1-15,33-47,17-31,49-63"
        OvsDpdkSocketMemory: "1024,1024"
        OvsDpdkMemoryChannels: "4"
        NovaReservedHostMemory: 4096
        OvsPmdCoreList: "1,33,17,49"
        OvsDpdkCoreList: "0,32,16,48"
        NovaVcpuPinSet: ['2-15','34-47','18-31','50-63']
        NovaComputeCpuSharedSet: "0,32,16,48"

    OvercloudControllerFlavor: "controller"
    OvercloudComputeOvsDpdkFlavor: "computeovsdpdk"

    ControllerCount: 1
    ComputeOvsDpdkCount: 1

    NeutronBridgeMappings: "datacentre:br-ex,data1:br-link0,data2:br-link1,provider:br-provider"
    NeutronFlatNetworks: "datacentre"
    NeutronNetworkVLANRanges: "data1:501:600,data2:501:600,provider:600:700"
    NeutronNetworkType: ['vxlan', 'vlan']
    NeutronTunnelTypes: "vxlan"
    NeutronPhysnetNUMANodesMapping: {data1: [0], data2: [0]}
    NeutronTunnelNUMANodes: [0]

    
resource_registry:
    OS::TripleO::ComputeOvsDpdk::Net::SoftwareConfig: vlans//computeovsdpdk.yaml
    OS::TripleO::Controller::Net::SoftwareConfig: vlans//controller.yaml
